on:

  workflow_dispatch:                      # Run manaual workflows

env:
  owner: "${{ github.repository_owner }}"  # Get owner name
  
jobs:

  disable-github-actions:                 # Job name "disable-github-actions"
    runs-on: ubuntu-latest                # OS selection for run
    steps:
      - name: Check out                   # step name "Check out"
        uses: actions/checkout@v3         # checkout repository
      - name: Create root directory       # step name "Create root directory"
        run: |                            # Run command line
          mkdir disable-github-actions
          cd disable-github-actions
      - name: Disable Github actions workflows  # step name "Disable Github actions workflows"
        shell: bash                             # Use bash shell
        env:                                    # Set environment variable
         GH_TOKEN: ${{ secrets.CD_PAT }}        # Environment name: GH_TOKEN, value= secret name CD_PAT
        run: |                                  # Run command line
          file="repo.txt"
          while read -r line; do
              echo "Processing repository $line"
              mkdir "$line"
              cd $line
              echo "echo Get workflows id"
              gh api \
              -H "Accept: application/vnd.github+json" \
              /repos/$owner/$line/actions/workflows | jq '.workflows | .[].id' >> $line-WorkflowId.txt
              echo "################################################################"
              echo "echo file $line-WorkflowId before insert string"
              cat $line-WorkflowId.txt
              echo "################################################################"
              echo "/repos/$owner/$line/actions/workflows/" >> $line-WorkflowPath.txt
              echo "echo file $line-WorkflowPath.txt"
              cat $line-WorkflowPath.txt
              echo "################################################################"
              ## replace workflow id
              sed -ie 's/^/\/repos\/'$owner'\/'$line'\/actions\/workflows\//' $line-WorkflowId.txt
              sed -ie 's/$/\/disable/' $line-WorkflowId.txt 
              echo "echo file $line-WorkflowId after insert string"
              cat $line-WorkflowId.txt
              echo "################################################################"
              echo "Disabling $line workflows"
              file=$line-WorkflowId.txt
              while read -r ID; do
                  gh api \
                   --method PUT \
                   -H "Accept: application/vnd.github+json" \
                   $ID
              done <$file
              echo "################################################################"
              echo "Disabled $line workflows"
              echo "################################################################"
              cd .. 
          done <$file

      - name: Get Github actions workflows status             # step name "Get Github actions workflows status"
        shell: bash                                           # Use bash shell
        env:                                                  # Set environment variable
         GH_TOKEN: ${{ secrets.CD_PAT }}                      # Environment name: GH_TOKEN, value= secret name CD_PAT
        run: |                                                # Run command line
          file="repo.txt"
          while read -r line; do
              cd $line
              gh api \
              -H "Accept: application/vnd.github+json" \
              /repos/$owner/$line/actions/workflows | jq '.workflows | .[].id' >> $line-StatusId.txt
              echo "Get $line workflows status"
              file=$line-StatusId.txt
              while read -r STATUS; do
                  echo ID=$(gh api \
                  -H "Accept: application/vnd.github+json" \
                   /repos/$owner/$line/actions/workflows/$STATUS | jq '.id') 
                  echo NAME=$(gh api \
                  -H "Accept: application/vnd.github+json" \
                   /repos/$owner/$line/actions/workflows/$STATUS | jq '.name')
                  echo STATUS=$(gh api \
                  -H "Accept: application/vnd.github+json" \
                   /repos/$owner/$line/actions/workflows/$STATUS | jq '.state')
                   echo "----------------------------------------------------------------"
              done <$file
              echo "#################################################################"
              cd .. 
          done <$file
